name: c28_bad_grp01
on:
  push:
    branches:
      - "*"
  workflow_dispatch:

env:
  POSTGRES_DB: c28_bad_grp01-test
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
          yarn knex migrate:latest --env test
          yarn test
  
  deploy:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      # - name: 'Create env file'
      #   run: |
      #     touch .env
      #     echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
      #     echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
      #     echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
      #     echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env
      #     echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> .env
      #     cat .env
          
      - name: ssh to pull latest version
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd hk-map-28-aug-23-sw-exercises/03_BAD/BAD003/review/memo-wall
            git pull origin main
            yarn install
            yarn knex migrate:latest --env production
            pm2 restart 0
          host: jameslam.me
          username: ubuntu
          port: 22
          key: ${{secrets.SSH_PRIVATE_KEY}}

  deploy-python:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: ssh to pull latest version
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd hk-map-28-aug-23-sw-exercises/03_BAD/BAD008/exercises/py-backend
            git pull origin main
            pm2 restart 1
          host: jameslam.me
          username: ubuntu
          port: 22
          key: ${{secrets.SSH_PRIVATE_KEY}}
