name: c28_bad_grp01
on:
  push:
    branches:
      - "*"
  workflow_dispatch:

env:
  POSTGRES_DB: c28_bad_grp01-test
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

  TEST__DB_NAME: memo_wall_testing
  TEST__DB_USERNAME: wall
  TEST__DB_PASSWORD: postgres
  TEST__DB_HOSTNAME: postgres
  TEST__DB_PORT: 5432
  
jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{env.TEST__DB_NAME}}
          POSTGRES_USER: ${{env.TEST__DB_USERNAME}}
          POSTGRES_PASSWORD: ${{env.TEST__DB_PASSWORD}}
          POSTGRES_PORT: ${{env.TEST__DB_PORT}}
          POSTGRES_HOST: ${{env.TEST__DB_HOSTNAME}}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
          yarn knex migrate:latest --env test
          yarn test
  deploy:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: ssh to pull latest version
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd V28-BAD-Proj-GP01
            git pull origin main
            yarn install
            yarn knex migrate:latest --env production
            pm2 restart V28-BAD-Proj-GP01 
          host: 46.51.223.210
          username: ubuntu
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}